### PR TITLE
[hotfix] Fix pom.xml and delete outdated files

### PR DESCRIPTION
**Pull request by zhipeng93**
## What is the purpose of the change
- make `mvn package` works and delete some code in the old Flink ML API (as opposed to FLIP-173)

## Brief change log
- fix bug in flink-ml-lib/pom.xml and flink-ml-uber/pom.xml
- delete the code that only works in old Flink ML API (e.g., EstimatorBase.java,ModelBase.java, PipelineStageBase.java, etc)

## Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (-)

### CODE REVIEW

**Comment by zhipeng93** [comment]
@becketqin can you take a quick look?

**Comment by lindong28** [comment]
Thanks for the PR. LGTM.

It may be cleaner to use the following words in the commit message and as the PR title:

`[hotfix] Fix pom.xml and delete outdated files`.

**Comment by lindong28** [comment]
Note that there is typically a space after the tag `[hotfix]`. The PR title typically does not end with `.`.

**Comment by zhipeng93** [comment]
> Note that there is typically a space after the tag `[hotfix]`. The PR title typically does not end with `.`.

Hi Dong, thanks for the review. The title is updated.

**Comment by zhipeng93** [comment]
Hi @gaoyunhaii can you take a look at this PR?

**Comment by gaoyunhaii** [comment]
Very thanks @zhipeng93 for opening the PR! LGTM and +1 to merge~

**Review by gaoyunhaii — APPROVED** [review]

**Pull request closed without merging**
