### PR TITLE
[FLINK-26263] (followup) Check data size in LogisticRegression

### PR DESCRIPTION
**Pull request by zhipeng93**
## What is the purpose of the change

- This is a followup of https://github.com/apache/flink-ml/pull/63

## Brief change log
- Put off the check of train data size and let each worker intanstiate variables even there is no input data.
- Get model dimension using parallelism 1.

## Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with @public(Evolving): (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (N/A)

### CODE REVIEW

**Comment by lindong28** [comment]
Thanks for PR! 

Could you confirm that the flaky test could be reproduced before this patch but not after this patch?

And could you update the AllReduceImpl's Java doc to replace `only one double array` with `up to one double array`? And maybe update allReduceSum() Java doc similarly?

**Comment by zhipeng93** [comment]
Hi Dong, Thanks for the review.

> Could you confirm that the flaky test could be reproduced before this patch but not after this patch?

I have repeatedly run this flaky test for up to 100 times and there is no failures.
Do you mean that we need another test case for this bug fix? I think `LogisticRegressionTest#testMoreSubtaskThanData` already covers this case --- It sometimes fails before, but did not fail for 100 runs after this fix.
 
> And could you update the AllReduceImpl's Java doc to replace `only one double array` with `up to one double array`? And maybe update allReduceSum() Java doc similarly?

The java doc is updated and I also added one more test case to cover this.

**Comment by lindong28** [comment]
@zhipeng93 It is generally preferred to have a test to reproduce this bug with high likelihood, or be able to reproduce this bug manually. This is generally done on a best-effort basis. The goal is to increase the confidence that we indeed fixed a bug with this PR.

If the flaky test is really hard to reproduce and there is no known way to cover the bug with a new test, we can still choose to merge the PR based on our understanding. This is just less than ideal.

**Comment by lindong28** [comment]
Thanks for the update! LGTM.

**Pull request closed without merging**
