### PR TITLE
[hotfix] Add scala suffix for dependencies in flink-ml-uber and flink-ml-lib as a dependency of flink-ml-uber

### PR DESCRIPTION
**Pull request by zhipeng93**
## What is the purpose of the change
- Add scala suffix for dependencies in flink-ml-uber and flink-ml-lib as a dependency of flink-ml-uber.

## Brief change log
- Add scala suffix for dependencies in flink-ml-uber
- Add flink-ml-lib as a dependency of flink-ml-uber

## Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (-)

### CODE REVIEW

**Comment by zhipeng93** [comment]
@gaoyunhaii @lindong28 Can you help review this PR?

**Comment by lindong28** [comment]
Thanks for the update. LGTM.

**Review by gaoyunhaii — APPROVED** [review]
LGTM

**Comment by gaoyunhaii** [comment]
Merged~

**Pull request closed without merging**
