### PR TITLE
[FLINK-31374] ProxyStreamPartitioner should implement ConfigurableStreamPartitioner

### PR DESCRIPTION
**Pull request by jiangxin369**
## What is the purpose of the change

Make the ProxyStreamPartitioner implement ConfigurableStreamPartitioner. Otherwise, the KeyGroupRange that is computed in StreamTaskStateInitializerImpl.java doesn't match the subTaskId that is computed in KeyGroupStreamPartitioner.java.

For more information, please refer to the [blog](https://flink.apache.org/2017/07/04/a-deep-dive-into-rescalable-state-in-apache-flink/).

## Brief change log

  - Make the ProxyStreamPartitioner implement ConfigurableStreamPartitioner.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by jiangxin369** [comment]
@zhipeng93 Could you help review this PR?

**Review by zhipeng93 — COMMENTED** [review]
Thanks for the fix :)  

LGTM. I left one minor comment there and will merge the PR after you resolve it.

**Comment by jiangxin369** [comment]
@zhipeng93 Thanks for the review, I've updated the PR.

**Comment by zhipeng93** [comment]
Thanks for the update. LGTM.

**Pull request merged**
